doctors.page_size=6
inventories.page_size=5
medicines.page_size=5
inventories.low_stock=100
services_disease=6
notifications_page_size=5

vnpay.returnUrl=http://localhost:8081/ClinicManagement/api/secure/payments/vnpay/callback
vnpay.tmnCode=R6X6GWUX
vnpay.hashSecret=WFIZP31SWRL39MQI9WO9WON93OP0BXIO
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html